# Generated by Django 5.0.6 on 2026-06-28 05:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('requires_design', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('enabled', '启用'), ('disabled', '停用')], default='enabled', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_no', models.CharField(max_length=40, unique=True)),
                ('platform_order_no', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交'), ('pending_design', '待设计'), ('designing', '设计中'), ('design_confirmed', '设计确认'), ('pending_production', '待生产安排'), ('completed', '已完成'), ('cancelled', '已取消')], default='draft', max_length=30)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_status', models.CharField(choices=[('unpaid', '未收款'), ('partial', '部分收款'), ('paid', '已收款')], default='unpaid', max_length=30)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('urgent', models.BooleanField(default=False)),
                ('customization_note', models.TextField(blank=True)),
                ('remark', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='customers.customer')),
                ('design_option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.designoption')),
                ('salesperson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='stores.store')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_name', models.CharField(max_length=200)),
                ('sku', models.CharField(blank=True, max_length=120)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('line_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('custom_size', models.CharField(blank=True, max_length=120)),
                ('custom_color', models.CharField(blank=True, max_length=120)),
                ('custom_note', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
        ),
        migrations.AddIndex(
            model_name='designoption',
            index=models.Index(fields=['status', 'sort_order'], name='orders_desi_status_56ddf7_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_no'], name='orders_orde_order_n_7a9a09_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['platform_order_no'], name='orders_orde_platfor_3946fb_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['store', 'status'], name='orders_orde_store_i_610c63_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer'], name='orders_orde_custome_59b6fb_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['salesperson'], name='orders_orde_salespe_7a577a_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['design_option'], name='orders_orde_design__14a21f_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['delivery_date'], name='orders_orde_deliver_e4274f_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='orders_orde_created_0e92de_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='orders_orde_status_25e057_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='orders_orde_order_i_5d347b_idx'),
        ),
    ]
