# Generated by Django 5.0.6 on 2026-06-28 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_company_customer_line_customer_source_and_more'),
        ('orders', '0001_initial'),
        ('stores', '0001_initial'),
        ('system_settings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='system_settings.paymentchannel'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_channel'], name='orders_orde_payment_a8fedf_idx'),
        ),
    ]
