# Generated by Django 5.0.6 on 2026-06-28 05:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_no', models.CharField(max_length=40, unique=True)),
                ('status', models.CharField(choices=[('pending', '待领取'), ('designing', '设计中'), ('waiting_confirmation', '待确认'), ('needs_changes', '需修改'), ('confirmed', '已确认')], default='pending', max_length=30)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('remark', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('designer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='design_task', to='orders.order')),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='design_desi_status_e581a2_idx'), models.Index(fields=['designer', 'status'], name='design_desi_designe_7e3f43_idx'), models.Index(fields=['due_at'], name='design_desi_due_at_bbc50d_idx')],
            },
        ),
    ]
