# Generated by Django 5.0.6 on 2026-06-28 07:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='company',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='customer',
            name='line',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='customer',
            name='source',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='customer',
            name='tags',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['source'], name='customers_c_source_f6c0b3_idx'),
        ),
    ]
