# Generated by Django 5.0.6 on 2026-06-30 04:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceTypeOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('code', models.SlugField(max_length=60, unique=True)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=13, max_digits=5)),
                ('sort_order', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('enabled', '启用'), ('disabled', '停用')], default='enabled', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['status', 'sort_order'], name='system_sett_status_98c6d2_idx')],
            },
        ),
    ]
