# Generated by Django 5.0.6 on 2026-06-28 06:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_no', models.CharField(max_length=40, unique=True)),
                ('invoice_type', models.CharField(choices=[('normal', '普票'), ('special', '专票')], default='normal', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('title', models.CharField(max_length=200)),
                ('tax_number', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending', '待审批'), ('approved', '已通过'), ('rejected', '已驳回'), ('withdrawn', '已撤回')], default='pending', max_length=30)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_applications', to=settings.AUTH_USER_MODEL)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_approvals', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_requests', to='customers.customer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_requests', to='orders.order')),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='finance_inv_status_f7004b_idx'), models.Index(fields=['customer'], name='finance_inv_custome_9f7059_idx'), models.Index(fields=['order'], name='finance_inv_order_i_1184b8_idx'), models.Index(fields=['applicant'], name='finance_inv_applica_c7532d_idx')],
            },
        ),
    ]
