# Generated by Django 5.0.6 on 2026-06-30 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_invoicerequest_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicerequest',
            name='invoice_type',
            field=models.CharField(choices=[('normal', '普通13%'), ('special', '专票13%')], default='normal', max_length=30),
        ),
    ]
