# Generated by Django 5.0.6 on 2026-06-28 06:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AfterSalesRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_no', models.CharField(max_length=40, unique=True)),
                ('type', models.CharField(choices=[('refund', '退款'), ('reship', '补发'), ('repair', '返修'), ('complaint', '投诉'), ('other', '其他')], max_length=30)),
                ('status', models.CharField(choices=[('pending', '待受理'), ('processing', '处理中'), ('completed', '已完成'), ('closed', '已关闭')], default='pending', max_length=30)),
                ('description', models.TextField()),
                ('solution', models.TextField(blank=True)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='after_sales_requests', to='orders.order')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='after_sales_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['order'], name='after_sales_order_i_9820b1_idx'), models.Index(fields=['status'], name='after_sales_status_b651cb_idx'), models.Index(fields=['owner', 'status'], name='after_sales_owner_i_43d96b_idx')],
            },
        ),
    ]
