# Generated by Django 5.0.6 on 2026-06-29 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='custom_platform',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
