# Generated by Django 5.0.6 on 2026-06-28 05:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionArrangement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arrangement_no', models.CharField(max_length=40, unique=True)),
                ('factory_name', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(choices=[('pending', '待安排'), ('scheduled', '已安排'), ('confirmed', '已确认'), ('exception', '异常')], default='pending', max_length=30)),
                ('planned_finish_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('remark', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='production_arrangement', to='orders.order')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='production__status_75128b_idx'), models.Index(fields=['owner', 'status'], name='production__owner_i_ed4006_idx'), models.Index(fields=['planned_finish_at'], name='production__planned_0c051c_idx')],
            },
        ),
    ]
